%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.10-1-gafd5cba on {{2018,2,5},{16,10,29}}

-ifndef(pb_mucbody).
-define(pb_mucbody, true).

-define(pb_mucbody_gpb_version, "3.18.10-1-gafd5cba").

-record('MUCBody.Status',
        {error_code,                    % = 1, {enum,'MUCBody.Status.ErrorCode'} (optional)
         description                    % = 2, string (optional)
        }).

-record('MUCBody.Setting',
        {name,                          % = 1, string (optional)
         desc,                          % = 2, string (optional)
         type,                          % = 3, {enum,'MUCBody.Setting.Type'} (optional)
         max_users,                     % = 4, int32 (optional)
         owner                          % = 5, string (optional)
        }).

%%-record('JID',
%%        {app_key,                       % = 1, string (optional)
%%         name,                          % = 2, string (optional)
%%         domain,                        % = 3, string (optional)
%%         client_resource                % = 4, string (optional)
%%        }).

-record('MUCBody',
        {muc_id,                        % = 1, {msg,'JID'} (optional)
         operation,                     % = 2, {enum,'MUCBody.Operation'} (optional)
         from,                          % = 3, {msg,'JID'} (optional)
         to = [],                       % = 4, [{msg,'JID'}]
         setting,                       % = 5, {msg,'MUCBody.Setting'} (optional)
         reason,                        % = 6, string (optional)
         is_chatroom,                   % = 7, bool (optional)
         status                         % = 8, {msg,'MUCBody.Status'} (optional)
        }).

-endif.
